### ISSUE TITLE
Samples vs SDK

### ISSUE THREAD

**Issue by pointerless** [MicrosoftDocs/partner-center-java-docs#18]
This started as a comment on my previous issue but I thought may be more effective as a second issue of slightly greater importance. The [Samples](https://github.com/Microsoft/Partner-Center-Java-Samples) contain many useful implementations that are also utilised in the examples above in this doc. In the Order Creation example, the line `IAggregatePartner partnerOperations = this.getContext().getUserPartnerOperations();` is presumably using the class `ScenarioContext` from the samples package. 
Additionally the example above it, Customer Creation, uses an undefined function in `PartnerCredentials` from the SDK that returns a `IAggregatePartner`. As far as I can see there is no such function.
I'm sorry if this is me not getting something or having read something; I have only been looking at these docs for a day or two. But it really seems like the samples should be the actual SDK and the SDK the internal implementation. Otherwise maybe at least the samples should be available on maven to make development easier?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e637e9-1ed9-9e13-bb78-539e36d531f9
* Version Independent ID: 9727d476-10e9-52cb-d3a0-43fd3b00b442
* Content: [Get started with development using the Partner Center SDK](https://docs.microsoft.com/en-us/java/partnercenter/get-started?view=partnercenter-1.8.1)
* Content Source: [docs-ref-conceptual/get-started.md](https://github.com/MicrosoftDocs/partner-center-java-docs/blob/live/docs-ref-conceptual/get-started.md)
* Service: **partener-center**
* GitHub Login: @isaiahwilliams

**Comment by pointerless** [comment]
Just to add to this, having taken a further look into it, I don't mean all the code in the samples. Just the interfaces and useful code that means trailing through everything is less complex. Or examples should be given without using code from them.

**Comment by indrasishg** [comment]
I am also facing the same issue. Why there is no solution suggested by ms as of now?

**Comment by pointerless** [comment]
I decided that they probably have little interest in maintaining the java sdk. I instead decided to just write my own interface to the rest api. Not the best long term solution but the only option I had. Sadly I also wrote it in node so I don't think sharing it would help. Try Spring Rest Templates in a module for your project? As long as you ensure everything is json, Jackson should do all the legwork.

**Comment by isaiahwilliams** [comment]
My apologizes for not responding to this sooner, I am not sure how I missed this issue. I have updated the get started documentation to address this concern. Also, I will be making more update in the near future that will make this guide more helpful. If you are still working with the Java SDK then I would recommend checking out the [sample project](https://github.com/microsoft/partner-center-java-samples).
